### ISSUE TITLE
ZW078 - b AU 921.42mhz. Does not include into homey at all

### ISSUE THREAD

**Issue by liteautomation1** [kentaclub/homey.aeotec#1]
The Heavy duty switch will not add into Homey. I have tried multiple times and either get the message that it failed, or if successful only ever is added as a Generic device because Homey can not find the relevant app. 
Part 1 when including,(the exclusion process) works immediately, but part 2 always ends in one of the above 2 scenarios. Majority of the time it is a failure to add.
Yes, the switch is within 200mm of the Homey during this process.
![Heavy Duty switch error 2](https://user-images.githubusercontent.com/43597556/75102931-f1f12180-5647-11ea-800f-3777b20b250e.PNG)
![Heavy Duty switch error](https://user-images.githubusercontent.com/43597556/75102932-f289b800-5647-11ea-96a0-8660c3b53747.PNG)
727a09ca-de9b-49d0-be53-09f1bc14413d diagnostic report

**Comment by kusanghi** [comment]
Updated the AU market device, try to reload the source and connect the device . Thanks
