### ISSUE TITLE
Can't install - non-existing ZW095-C

### ISSUE THREAD

**Issue by shaarkys** [kentaclub/homey.aeotec#2]
Hi,
it looks like ZW095-C is defined in app.json not available though in drivers.

> ✓ Pre-processing app...
✓ Validating app...
× Homey App did not validate against level `debug`:
Filepath does not exist: drivers\ZW095-C

**Comment by shaarkys** [comment]
When I removed ZW095-C relevant section, it's running now.
Looking forward to test ZW095-3C tomorrow, no idea why this great app isn't included by Athom ?

**Comment by kusanghi** [comment]
Thanks for the report, I fixed it
The default application will support ZW095-3C (3 phase).

ZW095-3C (3 phase) and ZW095-C (1 phase), all have the same ProductID, so use only 1 in 2 (if you use 3 phases, you cannot use 1 phase and vice versa).

If you use 3 phases, please see my [description](https://community.athom.com/t/aeotec-home-energy-meter-gen5-3-clamp/23927/4?u=baotran) at the forum.
