### ISSUE TITLE
Add support for ZW189-C15 Range Extender 7?

### ISSUE THREAD

**Issue by jofossheim** [kentaclub/homey.aeotec#3]
If there is any chance adding support for this device, I would be very happy.

**Comment by kusanghi** [comment]
Hi **jofossheim**,
Currently I do not have a device for testing.
But I rely on technical information from the Z-wavealliance, I will write more of this device.
Please re-download my update v 3.0.4. If it doesn't work please feedback, I'll fix it.
Thanks.

**Comment by jofossheim** [comment]
Thanks for the quick response! 
I tried it now three times, but unfortunately it just adds as a basic device, just like the official app when I try to add it as a Range extender 6. 

Also, the button needs to be pushed once, not twice.

**Comment by kusanghi** [comment]
You can take a screenshot of the application, after connecting to the Extender 7 device.

**Comment by jofossheim** [comment]
It reads: No compatible app found for this device. It is added as a basic z-wave device.

![IMG_0423](https://user-images.githubusercontent.com/63856469/80077577-f8b7ea00-854d-11ea-81de-f66a549ba17e.PNG)
![IMG_0424](https://user-images.githubusercontent.com/63856469/80077588-ff466180-854d-11ea-8262-634c99dcbb44.jpg)

**Comment by kusanghi** [comment]
Thanks,
In the specifications of Z-wavealliance, an information that is not provided is ManufacturerID provided, so I filled out the default number of Aeotec, possibly wrong, you can provide this information to me:
**Tap hold to device-> Setting-> Advanced settings. -> Z-Wave Device Infomation**, please capture all the information for me.

![ezgif-5-22b6d94a7ee4](https://user-images.githubusercontent.com/42129672/80079880-0b94e380-857b-11ea-8ff6-5528ad5b07af.gif)

**Comment by jofossheim** [comment]
![IMG_0427](https://user-images.githubusercontent.com/63856469/80080453-f192db00-8551-11ea-8dfb-7f31a6799091.PNG)

**Comment by jofossheim** [comment]
![IMG_0427](https://user-images.githubusercontent.com/63856469/80080524-0b342280-8552-11ea-924e-24c0bbab2322.PNG)

**Comment by kusanghi** [comment]
Updates, Please reload the new version.
Thanks

**Comment by jofossheim** [comment]
I might be doing something wrong, but I get the message "Homey App did not validate against level `debug`", so it won't install.

Thanks

**Comment by kusanghi** [comment]
Sorry, I named the version that does not match the structure of homey .
I have updated.

**Comment by jofossheim** [comment]
It works now. Thank you!
