### ISSUE TITLE
TriSensor: Motion detection is not working

### ISSUE THREAD

**Issue by KaareOlsen** [kentaclub/homey.aeotec#5]
The motion detection for TriSensor is not working. Lumens and temperature is working normally.

**Comment by kusanghi** [comment]
It still works fine with me. This is the image I tried to link to homey today.

![image](https://i.imgur.com/8fbAp69.jpg)

Please follow these steps.
1. Link Trisensor with Homey for the first time.
2. After pairing with homey, please. go to Trisensor's settings -> Advanced Settings -> Enable / Disable Binary Sensor Report -> select **Disable** -> Save
3. Go to Trisensor's settings -> Advanced Settings -> Enable / Disable Binary Sensor Report -> select **Enable** -> save. 
4. Remove the Trisensor battery, and reinsert the battery
5. Tap once on the pairing button of Trisensor, it will appear purple then turn off, go back to the Homey app and you will see the motion function will work. If it doesn't work, try step 5 again.
![image](https://i.imgur.com/Sz0l9jw.png)


Good lucky

**Comment by KaareOlsen** [comment]
Perfect! It worked! Thanks.
