### ISSUE TITLE
Update to SDK3 ?

### ISSUE THREAD

**Issue by shaarkys** [kentaclub/homey.aeotec#8]
Hi,
will you please update your app to SDK 3 ?
Seems modules like homey-meshdriver and homey-log works different now.

https://github.com/athombv/node-homey-meshdriver
https://github.com/athombv/node-homey-log

Thank you.

**Comment by kusanghi** [comment]
Hi, it's still in my update plan, a lot of my friends are also using, this is the first priority.
I am currently moving house, so all my equipment has not been installed for the new house. After stabilizing with the new house I will have time to update. I'll be back soon, very quickly.
Thank you for using my app.

**Comment by shaarkys** [comment]
No worries @kentaclub and thank you for your update ! Good luck with new place ;-)
